### ISSUE TITLE
Mono.TextEditor.Utils.TextFileUtility

### ISSUE THREAD

**Issue by RodrigoPereyraDiaz** [tpokorra/lbs-mono-fedora#14]
Fedora: 22 x86_64
Monodevelop: 5.7 build 660

When try to open any .cs file throw error:
"An exception was thrown by the type initializer for Mono.TextEditor.Utils.TextFileUtility"

**Comment by tpokorra** [comment]
I can confirm the problem on Fedora 21 x86_64 as well.

To get more debugging output, I started MonoDevelop from a terminal like this:
`monodevelop --no-redirect`

and then checked the file `~/.config/MonoDevelop/log`

the full stack trace for this error is:

```
ERROR [2015-04-22 08:33:54Z]: The file '/home/test/test/test/Program.cs' could not be opened. An exception was thrown by the type initializer for Mono.TextEditor.Utils.TextFileUtility
System.TypeInitializationException: An exception was thrown by the type initializer for Mono.TextEditor.Utils.TextFileUtility ---> System.NullReferenceException: Object reference not set to an instance of an object
  at Mono.TextEditor.Utils.TextFileUtility..cctor () [0x00000] in <filename unknown>:0
  --- End of inner exception stack trace ---
  at MonoDevelop.SourceEditor.SourceEditorView.Load (System.String fileName, System.Text.Encoding loadEncoding, Boolean reload) [0x00000] in <filename unknown>:0
  at MonoDevelop.SourceEditor.SourceEditorView.Load (System.String fileName) [0x00000] in <filename unknown>:0
  at MonoDevelop.Ide.Gui.LoadFileWrapper.Invoke (System.String fileName) [0x00000] in <filename unknown>:0
```

So the error happens in the constructor of `Mono.TextEditor.Utils.TextFileUtility`.
I am looking at the source https://github.com/mono/monodevelop/blob/master/main/src/core/Mono.Texteditor/Mono.TextEditor.Utils/TextFileUtility.cs#L42 but cannot see the problem...

Now I have created a simple test program that shows the same error:

```
using System.Text;
using System;
using System.Collections.Generic;

namespace test
{
    class Program
    {

        static int maxBomLength = 0;
        static Encoding[] encodingsWithBom;

        static void Main(string[] args)
        {
            var encodings = new List<Encoding> ();

            foreach (var info in Encoding.GetEncodings ()) {
Console.WriteLine("EncodingInfo name: " + info.Name);
                Encoding encoding;
                try {
                    encoding = info.GetEncoding ();
                } catch (NotSupportedException) {
                    continue;
                }
// this is where the Exception is thrown if no check for null
if (encoding == null) { Console.WriteLine("    is null"); continue; }
                var bom = encoding.GetPreamble ();

                if (bom == null || bom.Length == 0)
                    continue;
                maxBomLength = System.Math.Max (maxBomLength, bom.Length);
                encodings.Add (encoding);
            }
            encodingsWithBom = encodings.ToArray ();
        }
    }
}
```

so `info.GetEncoding()` sometimes returns null.

The output of this program is:

```
EncodingInfo name: IBM037
    is null
EncodingInfo name: IBM437
EncodingInfo name: IBM500
    is null
EncodingInfo name: ASMO-708
    is null
EncodingInfo name: ibm850
EncodingInfo name: ibm852
    is null
EncodingInfo name: IBM855
    is null
EncodingInfo name: ibm857
    is null
EncodingInfo name: IBM00858
    is null
EncodingInfo name: IBM860
EncodingInfo name: ibm861
EncodingInfo name: DOS-862
    is null
EncodingInfo name: IBM863
EncodingInfo name: IBM864
    is null
EncodingInfo name: IBM865
EncodingInfo name: cp866
    is null
EncodingInfo name: ibm869
    is null
EncodingInfo name: IBM870
    is null
EncodingInfo name: windows-874
    is null
EncodingInfo name: cp875
    is null
EncodingInfo name: shift_jis
    is null
EncodingInfo name: gb2312
    is null
EncodingInfo name: ks_c_5601-1987
    is null
EncodingInfo name: big5
    is null
EncodingInfo name: IBM1026
    is null
EncodingInfo name: IBM01047
    is null
EncodingInfo name: IBM01140
    is null
EncodingInfo name: IBM01141
    is null
EncodingInfo name: IBM01142
    is null
EncodingInfo name: IBM01143
    is null
EncodingInfo name: IBM01144
    is null
EncodingInfo name: IBM01145
    is null
EncodingInfo name: IBM01146
    is null
EncodingInfo name: IBM01147
    is null
EncodingInfo name: IBM01148
    is null
EncodingInfo name: IBM01149
    is null
EncodingInfo name: utf-16
EncodingInfo name: utf-16BE
EncodingInfo name: windows-1250
EncodingInfo name: windows-1251
    is null
EncodingInfo name: Windows-1252
EncodingInfo name: windows-1253
EncodingInfo name: windows-1254
    is null
EncodingInfo name: windows-1255
    is null
EncodingInfo name: windows-1256
    is null
EncodingInfo name: windows-1257
    is null
EncodingInfo name: windows-1258
    is null
EncodingInfo name: macintosh
EncodingInfo name: x-mac-icelandic
EncodingInfo name: utf-32
EncodingInfo name: utf-32BE
EncodingInfo name: us-ascii
EncodingInfo name: IBM273
    is null
EncodingInfo name: IBM277
    is null
EncodingInfo name: IBM278
    is null
EncodingInfo name: IBM280
    is null
EncodingInfo name: IBM284
    is null
EncodingInfo name: IBM285
    is null
EncodingInfo name: IBM290
    is null
EncodingInfo name: IBM297
    is null
EncodingInfo name: IBM420
    is null
EncodingInfo name: IBM424
    is null
EncodingInfo name: koi8-r
    is null
EncodingInfo name: IBM871
    is null
EncodingInfo name: cp1025
    is null
EncodingInfo name: koi8-u
    is null
EncodingInfo name: iso-8859-1
EncodingInfo name: iso-8859-2
EncodingInfo name: iso-8859-3
EncodingInfo name: iso-8859-4
    is null
EncodingInfo name: iso-8859-5
    is null
EncodingInfo name: iso-8859-6
    is null
EncodingInfo name: iso-8859-7
EncodingInfo name: iso-8859-8
    is null
EncodingInfo name: iso-8859-9
    is null
EncodingInfo name: iso-8859-15
EncodingInfo name: iso-8859-8-i
    is null
EncodingInfo name: iso-2022-jp
    is null
EncodingInfo name: csISO2022JP
    is null
EncodingInfo name: iso-2022-jp
    is null
EncodingInfo name: euc-jp
    is null
EncodingInfo name: euc-kr
    is null
EncodingInfo name: GB18030
    is null
EncodingInfo name: x-iscii-de
    is null
EncodingInfo name: x-iscii-be
    is null
EncodingInfo name: x-iscii-ta
    is null
EncodingInfo name: x-iscii-te
    is null
EncodingInfo name: x-iscii-as
    is null
EncodingInfo name: x-iscii-or
    is null
EncodingInfo name: x-iscii-ka
    is null
EncodingInfo name: x-iscii-ma
    is null
EncodingInfo name: x-iscii-gu
    is null
EncodingInfo name: x-iscii-pa
    is null
EncodingInfo name: utf-7
EncodingInfo name: utf-8
```

**Comment by tpokorra** [comment]
looking at https://github.com/mono/mono/blob/mono-4.0.0-branch/mcs/class/corlib/System.Text/EncodingInfo.cs#L76 and https://github.com/mono/mono/blob/mono-4.0.0-branch/mcs/class/corlib/System.Text/Encoding.cs#L416

In master, System.Text.Encoding is now based on the Microsoft Reference Sources. 
In Comparison: https://github.com/mono/mono/tree/master/mcs/class/corlib/System.Text 
In Comparison: https://github.com/mono/mono/tree/mono-3.12.0-branch/mcs/class/corlib/System.Text 

Since Mono 4.0.0 also references the reference sources, perhaps it is used there already?
see https://github.com/mono/referencesource/blob/mono-4.0.0-branch/mscorlib/system/text/encodinginfo.cs
and https://github.com/mono/referencesource/blob/mono-4.0.0-branch/mscorlib/system/text/encoding.cs#L396

I guess we can patch MonoDevelop for the moment, but we should report this upstream as well.
I am not sure yet if this is a Mono or MonoDevelop issue...

**Comment by tpokorra** [comment]
I came to the conclusion that this is a Mono issue, since MonoDevelop expects an exception to be thrown, if the Encoding is not supported.

I have filed a bug for Mono: https://bugzilla.xamarin.com/show_bug.cgi?id=29294
and added a patch for our Fedora Mono package

**Comment by tpokorra** [comment]
yes, locally built Mono 4.0.0-8 with the patch fixes this issue.
just uploaded to copr

**Comment by BenWiederhake** [comment]
I'm running into exactly this issue, even though above I'm using version 5.9.4., so the above patches are applied.

Occurred when: Opening any *.vb file.

Actual error message:
Datei '/home/eispin/workspace/portfolio-selection/Portfolio Selection/cls_Proportions.vb' konnte nicht geöffnet werden. An exception was thrown by the type initializer for Mono.TextEditor.Utils.TextFileUtility
An exception was thrown by the type initializer for Mono.TextEditor.Utils.TextFileUtility

Translated first sentence:
File '/home/eispin/workspace/portfolio-selection/Portfolio Selection/cls_Proportions.vb' could not be opened.

Environment: Debian Testing, first experience in VB.net, mono, and everything (so it might as well be my fault), on a fresh install of mono and mono develop from:
"deb http://download.mono-project.com/repo/debian wheezy main"
aptitude reports all mono-packages as version 4.0.2.5-0xamar, and monodevelop as version 5.9.4.5-0xamar

**Comment by BenWiederhake** [comment]
Turns out, I overlooked the package mono-complete. I don't really understand why this stopped me from opening a file, but now it works.

**Comment by tpokorra** [comment]
I should have linked the Xamarin bug here:

https://bugzilla.xamarin.com/show_bug.cgi?id=29294

The conclusion was to install the package mono-locale-extras.

**Comment by xasx** [comment]
@BenWiederhake @tpokorra Thanks for pointing this out.

**Comment by oymy** [comment]
@tpokorra Thanks for the information.
If using apt-get, libmono-i18n4.0-all is the right package to install.

**Comment by seith-miller** [comment]
For any one looking for a simple work around I solve this on my machine.

I am running Linux mint 16 

I ran...
sudo apt-get purge monodevelop
sudo apt-get autoremove
sudo apt-get install monodevelop
sudo apt-get install mono-devel

I hope this is helpful!
