### ISSUE TITLE
gnome-desktop-sharp don't build in EPEL7

### ISSUE THREAD

**Issue by RodrigoPereyraDiaz** [tpokorra/lbs-mono-fedora#16]
EPEL7 do not distribute gnome-desktop-devel instead only have gnome-desktop3-devel

All package depended on gnome-desktop-sharp do not build to.

**Comment by RodrigoPereyraDiaz** [comment]
Package depend on gnome-desktop-sharp
- monodevelop
- monodevelop-database

**Comment by tpokorra** [comment]
I have just installed a virtual machine with CentOS7 and our Monodevelop from copr, and it started fine.

So my workaround has worked, and we can use gnome-desktop3-devel on Epel 7
