### ISSUE TITLE
Building mono for CentOS/Epel: debuginfo package: No build ID note found

### ISSUE THREAD

**Issue by tpokorra** [tpokorra/lbs-mono-fedora#3]
```
+ /usr/lib/rpm/find-debuginfo.sh --strict-build-id -m --run-dwz --dwz-low-mem-die-limit 10000000 --dwz-max-die-limit 110000000 /builddir/build/BUILD/mono-4.0.0
extracting debug info from /builddir/build/BUILDROOT/mono-4.0.0-3.el7.centos.x86_64/usr/lib/mono/4.5/mscorlib.dll.so
*** ERROR: No build ID note found in /builddir/build/BUILDROOT/mono-4.0.0-3.el7.centos.x86_64/usr/lib/mono/4.5/mscorlib.dll.so
```

**Comment by tpokorra** [comment]
several options:
- https://lists.fedoraproject.org/pipermail/packaging/2011-May/007762.html
  - `%global _missing_build_ids_terminate_build 0`
  - does not work for me
- http://lists.ximian.com/pipermail/mono-devel-list/2010-September/035938.html: "Delete i386/usr/lib/mono/2.0/mscorlib.dll.so, its a generated file, and shouldn't be included in the final package"
- http://lists.ximian.com/pipermail/mono-devel-list/2013-August/040793.html %global debug_package %{nil}

**Comment by tpokorra** [comment]
solution currently: for el6 and el7 packages, do not build a debug_package

**Comment by omajid** [comment]
FWIW, the magic invocation seems to be `%undefine _missing_build_ids_terminate_build`, not `%global _missing_build_ids_terminate_build 0`. [This document](http://pkgbuild.sourceforge.net/spec-files.txt) explains that `%{?foo:fred}` is evaluated as `fred` if `foo` is defined (to any value) but as nothing if `foo` is undefined.

**Comment by tpokorra** [comment]
thank you @omajid! I have adjusted my spec file accordingly, and this helps when I want to push a new version of Mono to Epel at some point during this year 2016.

**Comment by miradnan** [comment]
thank you @omajid! It works...

**Comment by SergioDevAlcalde** [comment]
thanks @omajid
